services:
  - type: web
    name: skywatch-ua
    env: node
    plan: free
    buildCommand: apt-get update && apt-get install -y imagemagick && npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
